export const stats = [
  { label: "Total Posts", value: "1,247", change: "+12.5%", trend: "up" as const },
  { label: "Total Views", value: "3.2M", change: "+18.2%", trend: "up" as const },
  { label: "Engagement Rate", value: "4.8%", change: "+0.3%", trend: "up" as const },
  { label: "Followers Gained", value: "12,847", change: "+7.1%", trend: "up" as const },
];

export const recentActivity = [
  { id: 1, type: "post" as const, message: "New post published: \"10 Tips for Better Content\"", time: "2 min ago", status: "success" as const },
  { id: 2, type: "comment" as const, message: "New comment from @sarah_designs", time: "15 min ago", status: "info" as const },
  { id: 3, type: "automation" as const, message: "Auto-reply sent to 3 comments", time: "1 hour ago", status: "success" as const },
  { id: 4, type: "error" as const, message: "Failed to post scheduled content", time: "2 hours ago", status: "error" as const },
  { id: 5, type: "post" as const, message: "Draft saved: \"Behind the Scenes\"", time: "3 hours ago", status: "info" as const },
  { id: 6, type: "client" as const, message: "New client added: TechCorp Inc.", time: "5 hours ago", status: "success" as const },
];

export const calendarEvents = [
  { id: 1, title: "Product Launch Video", date: "2026-09-01", time: "10:00 AM", platform: "TikTok", status: "scheduled" as const, type: "video" as const },
  { id: 2, title: "Behind the Scenes Reel", date: "2026-09-02", time: "2:00 PM", platform: "TikTok", status: "scheduled" as const, type: "reel" as const },
  { id: 3, title: "Q&A Response Video", date: "2026-09-03", time: "11:00 AM", platform: "TikTok", status: "draft" as const, type: "video" as const },
  { id: 4, title: "Trend Challenge Participation", date: "2026-09-04", time: "3:00 PM", platform: "TikTok", status: "scheduled" as const, type: "video" as const },
  { id: 5, title: "Weekly Tips Carousel", date: "2026-09-05", time: "9:00 AM", platform: "TikTok", status: "published" as const, type: "image" as const },
  { id: 6, title: "User Testimonial Compilation", date: "2026-09-06", time: "1:00 PM", platform: "TikTok", status: "draft" as const, type: "video" as const },
  { id: 7, title: "How-To Tutorial Series", date: "2026-09-07", time: "10:00 AM", platform: "TikTok", status: "scheduled" as const, type: "video" as const },
];

export const posts = [
  {
    id: 1,
    title: "10 Tips for Better Content Creation",
    content: "Creating engaging content doesn't have to be hard. Here are my top 10 tips...",
    platform: "TikTok",
    status: "published" as const,
    scheduledDate: "2026-08-30",
    likes: 12400,
    comments: 342,
    shares: 890,
    views: 245000,
    thumbnail: null,
  },
  {
    id: 2,
    title: "Behind the Scenes: Our Studio Setup",
    content: "Ever wondered where the magic happens? Take a peek behind the curtain...",
    platform: "TikTok",
    status: "scheduled" as const,
    scheduledDate: "2026-09-02",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    thumbnail: null,
  },
  {
    id: 3,
    title: "Q&A: Answering Your Top Questions",
    content: "You asked, we answered! Here are responses to your most popular questions...",
    platform: "TikTok",
    status: "draft" as const,
    scheduledDate: null,
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    thumbnail: null,
  },
  {
    id: 4,
    title: "Trending Dance Challenge 2026",
    content: "Jumping on the latest trend! Here's our take on the viral dance challenge...",
    platform: "TikTok",
    status: "published" as const,
    scheduledDate: "2026-08-28",
    likes: 45200,
    comments: 1230,
    shares: 3400,
    views: 890000,
    thumbnail: null,
  },
  {
    id: 5,
    title: "Product Review: New Tech Gadget",
    content: "Is this gadget worth the hype? Let's break it down together...",
    platform: "TikTok",
    status: "scheduled" as const,
    scheduledDate: "2026-09-04",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    thumbnail: null,
  },
  {
    id: 6,
    title: "Day in the Life of a Creator",
    content: "Follow me through a typical day of content creation, meetings, and editing...",
    platform: "TikTok",
    status: "published" as const,
    scheduledDate: "2026-08-25",
    likes: 67800,
    comments: 2100,
    shares: 5600,
    views: 1200000,
    thumbnail: null,
  },
];

export const comments = [
  {
    id: 1,
    author: "@sarah_designs",
    avatar: "SD",
    content: "This is exactly what I needed! Thank you so much for sharing these tips 🙏",
    post: "10 Tips for Better Content Creation",
    time: "15 min ago",
    sentiment: "positive" as const,
    replied: false,
  },
  {
    id: 2,
    author: "@techguru_mike",
    avatar: "TM",
    content: "Great video but I think tip #5 could use more explanation",
    post: "10 Tips for Better Content Creation",
    time: "1 hour ago",
    sentiment: "neutral" as const,
    replied: false,
  },
  {
    id: 3,
    author: "@creative_luna",
    avatar: "CL",
    content: "Love your content! Would love to see a tutorial on editing 🎬",
    post: "Behind the Scenes: Our Studio Setup",
    time: "2 hours ago",
    sentiment: "positive" as const,
    replied: true,
  },
  {
    id: 4,
    author: "@skeptic_joe",
    avatar: "SJ",
    content: "Not sure this applies to everyone, my niche is different",
    post: "10 Tips for Better Content Creation",
    time: "3 hours ago",
    sentiment: "neutral" as const,
    replied: false,
  },
  {
    id: 5,
    author: "@fan_anna",
    avatar: "FA",
    content: "You're crushing it! The dance challenge was 🔥🔥🔥",
    post: "Trending Dance Challenge 2026",
    time: "5 hours ago",
    sentiment: "positive" as const,
    replied: true,
  },
  {
    id: 6,
    author: "@marketing_pro",
    avatar: "MP",
    content: "Could you share more details about the lighting setup?",
    post: "Behind the Scenes: Our Studio Setup",
    time: "8 hours ago",
    sentiment: "neutral" as const,
    replied: false,
  },
  {
    id: 7,
    author: "@newbie_creator",
    avatar: "NC",
    content: "Just started my journey and this is SO helpful! Following!",
    post: "Day in the Life of a Creator",
    time: "12 hours ago",
    sentiment: "positive" as const,
    replied: true,
  },
  {
    id: 8,
    author: "@angry_user",
    avatar: "AU",
    content: "This is clickbait, nothing useful here",
    post: "Trending Dance Challenge 2026",
    time: "1 day ago",
    sentiment: "negative" as const,
    replied: false,
  },
];

export const automations = [
  {
    id: 1,
    name: "Auto-Reply to Positive Comments",
    description: "Automatically responds to positive comments with a thank-you message",
    trigger: "New positive comment",
    action: "Send auto-reply",
    status: "active" as const,
    runs: 342,
    lastRun: "5 min ago",
    successRate: 98.5,
  },
  {
    id: 2,
    name: "Welcome New Followers",
    description: "Sends a welcome DM to accounts that follow you",
    trigger: "New follower",
    action: "Send welcome DM",
    status: "active" as const,
    runs: 1247,
    lastRun: "2 min ago",
    successRate: 95.2,
  },
  {
    id: 3,
    name: "Post Schedule Reminder",
    description: "Notifies you 30 minutes before a scheduled post",
    trigger: "30 min before scheduled post",
    action: "Send notification",
    status: "active" as const,
    runs: 89,
    lastRun: "1 hour ago",
    successRate: 100,
  },
  {
    id: 4,
    name: "Flag Negative Comments",
    description: "Flags potentially harmful or negative comments for review",
    trigger: "New comment",
    action: "Flag for review",
    status: "paused" as const,
    runs: 56,
    lastRun: "2 days ago",
    successRate: 87.5,
  },
  {
    id: 5,
    name: "Weekly Analytics Report",
    description: "Generates and sends a weekly performance summary",
    trigger: "Every Monday at 9:00 AM",
    action: "Generate report",
    status: "active" as const,
    runs: 12,
    lastRun: "3 days ago",
    successRate: 100,
  },
];

export const analyticsData = {
  viewsOverTime: [
    { date: "Aug 26", views: 45000 },
    { date: "Aug 27", views: 52000 },
    { date: "Aug 28", views: 89000 },
    { date: "Aug 29", views: 67000 },
    { date: "Aug 30", views: 120000 },
    { date: "Aug 31", views: 98000 },
    { date: "Sep 1", views: 75000 },
  ],
  engagementByType: [
    { type: "Likes", count: 125400, percentage: 65 },
    { type: "Comments", count: 3672, percentage: 12 },
    { type: "Shares", count: 9890, percentage: 23 },
  ],
  topPosts: [
    { title: "Day in the Life of a Creator", views: 1200000, likes: 67800, engagement: "6.2%" },
    { title: "Trending Dance Challenge 2026", views: 890000, likes: 45200, engagement: "5.8%" },
    { title: "10 Tips for Better Content", views: 245000, likes: 12400, engagement: "5.2%" },
  ],
  audienceGrowth: [
    { date: "Week 1", followers: 45000 },
    { date: "Week 2", followers: 48200 },
    { date: "Week 3", followers: 52100 },
    { date: "Week 4", followers: 57847 },
  ],
  demographics: {
    age: [
      { range: "13-17", percentage: 8 },
      { range: "18-24", percentage: 42 },
      { range: "25-34", percentage: 31 },
      { range: "35-44", percentage: 14 },
      { range: "45+", percentage: 5 },
    ],
    gender: [
      { type: "Female", percentage: 58 },
      { type: "Male", percentage: 38 },
      { type: "Other", percentage: 4 },
    ],
    topLocations: [
      { city: "New York", percentage: 12 },
      { city: "Los Angeles", percentage: 9 },
      { city: "London", percentage: 7 },
      { city: "Toronto", percentage: 5 },
      { city: "Sydney", percentage: 4 },
    ],
  },
};

export const clients = [
  {
    id: 1,
    name: "TechCorp Inc.",
    industry: "Technology",
    status: "active" as const,
    postsManaged: 24,
    followers: 156000,
    engagement: "4.2%",
    revenue: "$2,400/mo",
    nextPost: "2026-09-02",
    avatar: "TC",
  },
  {
    id: 2,
    name: "GreenLeaf Organics",
    industry: "Health & Wellness",
    status: "active" as const,
    postsManaged: 18,
    followers: 89000,
    engagement: "5.1%",
    revenue: "$1,800/mo",
    nextPost: "2026-09-03",
    avatar: "GL",
  },
  {
    id: 3,
    name: "UrbanStyle Fashion",
    industry: "Fashion",
    status: "active" as const,
    postsManaged: 31,
    followers: 234000,
    engagement: "3.8%",
    revenue: "$3,200/mo",
    nextPost: "2026-09-01",
    avatar: "US",
  },
  {
    id: 4,
    name: "FitnessPro Studio",
    industry: "Fitness",
    status: "paused" as const,
    postsManaged: 12,
    followers: 67000,
    engagement: "6.3%",
    revenue: "$1,200/mo",
    nextPost: null,
    avatar: "FP",
  },
  {
    id: 5,
    name: "Artisan Coffee Co.",
    industry: "Food & Beverage",
    status: "active" as const,
    postsManaged: 15,
    followers: 45000,
    engagement: "4.9%",
    revenue: "$1,500/mo",
    nextPost: "2026-09-04",
    avatar: "AC",
  },
  {
    id: 6,
    name: "Wanderlust Travel",
    industry: "Travel",
    status: "prospect" as const,
    postsManaged: 0,
    followers: 312000,
    engagement: "N/A",
    revenue: "Pending",
    nextPost: null,
    avatar: "WT",
  },
];

export const tiktokAccount = {
  username: "@postpilot_ai",
  displayName: "PostPilot AI",
  followers: 57847,
  following: 234,
  likes: 892400,
  videos: 247,
  verified: true,
  bio: "AI-powered content management for creators 🚀",
  profileViews: 125000,
  isProAccount: true,
  connected: false,
};
